<?php

namespace AppBundle\Repository;

/**
 * cvItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cvItemRepository extends \Doctrine\ORM\EntityRepository
{
}
